### ISSUE TITLE
Add synonyms to the Event columns.

### ISSUE THREAD

**Issue by vijai3d** [archscorer/archscorer#35]
Problem.

Currently, column headers for the Event participants list have names that are not fully understandable for some archers.
![image](https://user-images.githubusercontent.com/5159321/153541588-c753796d-74a9-4103-a03d-e9ceb7c4b229.png)

Proposal.

Add synonyms to them with a slash.

Group/Session
End/Target
Position/Index

**Comment by adlerpriit** [comment]
I believe this is solved now by #45. No slashes, but should be understandable now.
